platform :ios, '10.0'

target 'ProductViewer' do
  project 'ProductViewer/ProductViewer.xcodeproj'
  workspace 'TargetCaseStudy.xcworkspace'

  use_frameworks!
  pod 'Alamofire', '~> 5.4.1'
  pod 'AlamofireImage', '~> 4.1.0'
end
